name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: build on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Premake
      run: sudo ./premake/premake5 gmake2
    - name: Build with make
      run: sudo make
  build_windows:
    name: build on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Premake
      run: .\premake\premake5.exe gmake2
    - name: Build with make
      run: make
  build_macos:
    name: build on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Premake
      run: sudo ./premake/premake5 gmake2
    - name: Build with make
      run: sudo make
