name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: build on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Premake
      run: |
        chmod +x ./GenerateProject.sh
        chmod +x ./premake/premake5.out
        ./GenerateProject.sh
    - name: Build with make
      run: |
        make config=debug
        make config=release
  build_windows:
    name: build on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # We have to make these ourselves, because the windows vm still runs a linux shell (which doesn't make sub-directories automatically without the -p parameter)
    - name: make build folders
      run: |
        mkdir bin/
        mkdir bin-int/
    - name: Premake
      run: .\premake\premake5.exe gmake2
    - name: Build with make
      run: |
        make config=debug
        make config=release
